import React from 'react';

const EmployeePerformance = ({ employees }) => {
  return (
    <div className="card-neon animate-fade-in animate-delay-3" style={{ height: '400px', display: 'flex', flexDirection: 'column' }}>
      <div style={{ marginBottom: '1.5rem' }}>
        <h3 style={{ fontSize: '1.25rem', fontWeight: 800, color: '#fff', letterSpacing: '-0.5px' }}>Top Performers</h3>
        <p style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>Revenue generated by rep</p>
      </div>

      <div style={{ flex: 1, display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
        {employees.map((emp, idx) => (
          <div key={emp.name} style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
            <div style={{ 
              width: '40px', height: '40px', borderRadius: '50%', background: 'rgba(255,255,255,0.05)', 
              display: 'flex', alignItems: 'center', justifyContent: 'center', 
              fontWeight: 700, color: emp.color, border: `1px solid ${emp.color}40`,
              boxShadow: `0 0 10px ${emp.color}40`
            }}>
              {emp.avatar}
            </div>
            
            <div style={{ flex: 1 }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '0.4rem' }}>
                <div style={{ fontSize: '0.9rem', fontWeight: 600, color: '#fff' }}>{emp.name}</div>
                <div style={{ fontSize: '0.9rem', fontWeight: 700, color: emp.color }}>
                  ₹{Number(emp.revenue).toLocaleString('en-IN')}
                </div>
              </div>
              
              <div style={{ height: '6px', background: 'rgba(255,255,255,0.05)', borderRadius: '3px', overflow: 'hidden' }}>
                <div style={{ 
                  height: '100%', width: `${emp.percentage}%`, background: emp.color, borderRadius: '3px',
                  boxShadow: `0 0 8px ${emp.color}`,
                  animation: `fadeInUp 0.8s ease forwards ${idx * 0.15}s`
                }}></div>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default EmployeePerformance;
